### ISSUE TITLE
Trying to use singlestore with phidata and i keep getting this error, Even if i have done everything right with the right ssl certificate:I keep getting this error: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'svc-3482219c-a389-4079-b18b-d50662524e8a-shared-dml.aws-virginia-6.svc.singlestore.com' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000))")

### ISSUE THREAD

**Issue by ayofluxx** [phidatahq/phidata#197] opened 2024-04-28 11:20 UTC

**Comment by ashpreetbedi** [comment] 2024-04-28 17:58
@ayofluxx just checkign are you adding the certificate? [described here](https://github.com/phidatahq/phidata/tree/main/cookbook/integrations/singlestore/ai_apps#3-add-credentials)

**Comment by ayofluxx** [comment] 2024-04-28 18:06
> @ayofluxx just checkign are you adding the certificate? [described here](https://github.com/phidatahq/phidata/tree/main/cookbook/integrations/singlestore/ai_apps#3-add-credentials)

Yes I added the exact certificate and I'm still getting the same error.

**Comment by ashpreetbedi** [comment] 2024-04-28 22:17
@ayofluxx any chance you can do a sample query against the database? we've been testing this and everything seems to be on points. @vishwajeetdabholkar any insight?

**Comment by ashpreetbedi** [comment] 2024-04-30 22:03
will be closing for now as we cannot reproduce. please open if needed

**Closed by ashpreetbedi** 2024-04-30 22:03 UTC
