### ISSUE TITLE
Runtime example error

### ISSUE THREAD

**Issue by Rainismer** [phidatahq/phidata#1452] opened 2024-11-15 07:11 UTC
`from phi.agent import Agent
from phi.model.openai import OpenAIChat
from phi.tools.duckduckgo import DuckDuckGo

llm_4o = OpenAIChat(
    temperature=0,
    id="gpt-4o",
    api_key="xxxxxxxxxxxxxxxxxxxx=",
    base_url="http://10.100.100.100:10000/v1",
)

web_agent = Agent(
    name="Web Agent",
    model=llm_4o,
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)
web_agent.print_response("Whats happening in France?", stream=True)`

******************************************************************************************************************

**Traceback (most recent call last):
  File "D:\AIGC\idataai_py\test\experiment.py", line 49, in <module>
    web_agent.print_response("Whats happening in France?", stream=True)
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\phi\agent\agent.py", line 2605, in print_response
    for resp in self.run(message=message, messages=messages, stream=True, **kwargs):
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\phi\agent\agent.py", line 1610, in _run
    for model_response_chunk in self.model.response_stream(messages=messages_for_model):
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\phi\model\openai\chat.py", line 836, in response_stream
    _tool_calls = self._build_tool_calls(stream_data.response_tool_calls)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\phi\model\openai\chat.py", line 941, in _build_tool_calls
    if len(tool_calls) <= _index:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'**

**Comment by Rainismer** [comment] 2024-11-18 01:23
@manthanguptaa They are all the latest. But the problem still exists.

**Comment by manthanguptaa** [comment] 2024-11-18 11:02
Can you try removing `base_url` and try again?

**Comment by Rainismer** [comment] 2024-11-19 01:30
@manthanguptaa If using the native OpenAI API there is no problem, but in the company we must use a self-hosted API, so please have your team fix the proxy error as soon as possible.

**Comment by Rainismer** [comment] 2024-11-19 01:36
@manthanguptaa You can refer to litellm's approach

**Comment by ysolanky** [comment] 2024-11-30 06:21
Hello @Rainismer!

The error you shared indicates that the model is not returning tool calls in the required format. I am having trouble recreating that error. I self hosted an API endpoint that forwards to `https://api.openai.com/v1`. Here is the Agent config:

```python
from os import getenv
from phi.agent import Agent
from phi.model.openai import OpenAIChat
from phi.tools.duckduckgo import DuckDuckGo

agent = Agent(model=OpenAIChat(id="gpt-4o", base_url="http://127.0.0.1:10000/v1", api_key=getenv("OPENAI_API_KEY")), tools=[DuckDuckGo()], markdown=True)
agent.print_response("Whats happening in France?", stream=True)
```

But it is working as expected for me. Could you please:

- Share the debug logs
- Set `stream=False` and try again
- Try running the Agent without tools

Apologies for the delay in response. Looking to get this fixed for you ASAP

**Comment by Rainismer** [comment] 2024-12-02 02:53
@ysolanky I found that it can run normally without tools, but why is that? Is this a bug in the agent?

**Comment by ysolanky** [comment] 2024-12-02 16:33
@Rainismer It seems the response from your self-hosted endpoint is being modified in some way, which is causing the issue.

In our implementation, we capture tool calls using the response.choices[0].delta.tool_calls variable. The tool_calls contains chunks that look like this:
ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='{"sy', name=None), type=None),.

Based on the error you're encountering, it appears that the tool call chunks are not maintaining the expected format as returned by the OpenAI API. I attempted to replicate the error by self-hosting but was unable to reproduce it.

If you can share the contents of the stream_data.response_tool_calls variable from your endpoint, I’d be happy to assist further in resolving this issue.

**Comment by Rainismer** [comment] 2024-12-03 02:33
@ysolanky Thank you for your reply! Now I can call the tool normally by setting stream to False. What should I do if I want to enable streaming output?

**Comment by Rainismer** [comment] 2024-12-05 01:49
@ysolanky I found the cause of the error and fixed it, thank you for your help!

**Closed** 2024-12-05 01:50 UTC
